### ISSUE TITLE
Hinweisgebersystem

### ISSUE THREAD

**Issue by uni-it-law** [RRZE-Webteam/rrze-legal#62]
Vorschlag für ein Textbaustein:

```
### Mitteilungen von Informationen über Verstöße
Die Meldung von Verstößen durch Hinweisgeber kann entscheidend dazu beitragen, Risiken für die öffentliche Gesundheit und den Verbraucherschutz, die aus andernfalls womöglich unbemerkten Verstößen gegen Rechtsvorschriften erwachsen, aufzudecken, zu verhindern, einzudämmen oder zu beseitigen. 

### Meldewege
Bitte beachten Sie, dass anonyme Meldungen zwar möglich sind, aber nachrangig bearbeitet werden.
Davon unabhängig schützen die Meldestellen im Rahmen der gesetzlichen Anforderungen die Identität des Hinweisgebers.

#### Interne Meldestelle
- Link zum Hinweisgebersystem 
/ alt Ende zu Ende Verschlüsseltes Kontaktformular mit Rückkanal
/opt - Telefonnummer [Nicht empfohlen]
/opt - Briefkasten
Informationen zur Datenverarbeitung über den internen Meldeweg [Link].
/opt Der interne Meldeweg wird von einem externen, neutralen Mittler realisiert.
#### Externe Meldewege
Der Freistaat betreibt zudem auch ein externe Meldestelle [Link]
--


```

**Comment by xwolfde** [comment]
@uni-it-law Würde das zum Impressum gehören? Wenn ja, an welcher Stelle?

**Comment by uni-it-law** [comment]
@xwolfde Ist aus meiner Sicht zu individuell. Daher würde ich wenn, nur den jeweilige Themenseite verlinken.
Hinweisgebersystem

Vorschlag

### Mitteilungen von Informationen über Verstöße gemäß Hinweisgeberschutzgesetz
Die Meldung von Verstößen durch Hinweisgeber kann entscheidend dazu beitragen, Risiken für die öffentliche Gesundheit und den Verbraucherschutz, die aus andernfalls womöglich unbemerkten Verstößen gegen Rechtsvorschriften erwachsen, aufzudecken, zu verhindern, einzudämmen oder zu beseitigen. 

#### Interne Meldestelle
- Link zum Hinweisgebersystem

**Comment by xwolfde** [comment]
@rvdforst Wir bräuchten für die Impressumsseite ein Eingabefeld für eine URL für obigen Hinweisgeberschutz. Wenn das Feld mit einer gültigen URL ausgefüllt wurde, wird dann obiger Textbaustein mit der URL als Link mit ausgegeben.

**Comment by rvdforst** [comment]
@xwolfde @uni-it-law An welcher genauen Stelle soll der neue Textblock angezeigt werden? Vorschlag: Nach dem Inhalt des Feldes  „Hinzufügen eines neuen Abschnitts“?
Eine englische Übersetzung des Textes ist ebenfalls erforderlich. Vorschlag (KI Übersetzung):

### Communications of information about violations according to the Whistleblower Protection Act

The reporting of violations by whistleblowers can play a crucial role in uncovering, preventing, containing, or eliminating risks to public health and consumer protection that may arise from otherwise potentially unnoticed violations of legal provisions.

**Internal Reporting Office**

- Link to the whistleblower system

**Comment by xwolfde** [comment]
Ich würde es der Einfachheit einfach halber am Ende der Template hinzufügen. Also nach Zeile 169
https://github.com/RRZE-Webteam/rrze-legal/blob/main/templates/tos/imprint-de.html
sowas wie

{{=imprint_hinweisgebertext}}

**Comment by rvdforst** [comment]
Ist erledigt und eingespielt. Vgl. https://github.com/RRZE-Webteam/rrze-legal/pull/106/commits/29e65e9c045d08d0cc5bcb1689f913ec2465fcfd
